// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
import "./lib/Security.sol";
import "./AttendXWorldID.sol";
import "./AttendXRewards.sol";
contract AttendXCore is Ownable, ReentrancyGuard, Pausable { using SafeERC20 for IERC20;
    enum RewardModel{Fixed,Apy} struct EventConfig{string title;string description;uint64 startTime;uint64 endTime;uint256 stakeAmount;uint32 maxParticipants;uint256 rewardPool;uint256 fixedReward;uint256 apyBps;RewardModel rewardModel;bool closed;uint32 participants;}
    struct Position{uint256 amount;uint64 stakedAt;bool attended;bool withdrawn;bool rewardClaimed;}
    IERC20 public immutable stakingToken; AttendXWorldID public immutable worldId; uint256 public nextEventId=1; uint256 public slashBps=5_000;
    mapping(uint256=>EventConfig) public events; mapping(uint256=>mapping(address=>Position)) public positions;
    event EventCreated(uint256 indexed eventId,string title,uint64 start,uint64 end,uint256 stakeAmount); event Staked(address indexed user,uint256 indexed eventId,uint256 amount); event AttendanceMarked(address indexed user,uint256 indexed eventId); event StakeWithdrawn(address indexed user,uint256 indexed eventId,uint256 amount); event RewardClaimed(address indexed user,uint256 indexed eventId,uint256 amount); event EventClosed(uint256 indexed eventId);
    constructor(IERC20 token,AttendXWorldID verifier,address owner) Ownable(owner){stakingToken=token;worldId=verifier;}
    function createEvent(string calldata title,string calldata description,uint64 start,uint64 end,uint256 stakeAmount,uint32 maxParticipants,uint256 rewardPool,uint256 fixedReward,uint256 apyBps,RewardModel model) external onlyOwner returns(uint256 id){require(start<end && end>block.timestamp,"bad time");require(maxParticipants>0,"bad cap");if(rewardPool>0) stakingToken.safeTransferFrom(msg.sender,address(this),rewardPool); id=nextEventId++; events[id]=EventConfig(title,description,start,end,stakeAmount,maxParticipants,rewardPool,fixedReward,apyBps,model,false,0); emit EventCreated(id,title,start,end,stakeAmount);}
    function stake(uint256 eventId) external nonReentrant whenNotPaused {require(worldId.isVerified(msg.sender),"World ID required"); EventConfig storage e=events[eventId]; require(!e.closed && block.timestamp<e.startTime,"not joinable"); require(e.participants<e.maxParticipants,"full"); Position storage p=positions[eventId][msg.sender]; require(p.amount==0,"already joined"); e.participants++; p.amount=e.stakeAmount; p.stakedAt=uint64(block.timestamp); stakingToken.safeTransferFrom(msg.sender,address(this),e.stakeAmount); emit Staked(msg.sender,eventId,e.stakeAmount);}
    function markAttendance(uint256 eventId,address attendee) external onlyOwner {EventConfig storage e=events[eventId]; require(block.timestamp>=e.startTime && block.timestamp<=e.endTime,"outside window"); Position storage p=positions[eventId][attendee]; require(p.amount>0,"no stake"); p.attended=true; emit AttendanceMarked(attendee,eventId);}
    function withdrawStake(uint256 eventId) external nonReentrant {EventConfig storage e=events[eventId]; require(block.timestamp>e.endTime || e.closed,"locked"); Position storage p=positions[eventId][msg.sender]; require(p.amount>0 && !p.withdrawn,"none"); p.withdrawn=true; uint256 payout=p.attended ? p.amount : p.amount - (p.amount*slashBps/10_000); stakingToken.safeTransfer(msg.sender,payout); emit StakeWithdrawn(msg.sender,eventId,payout);}
    function claimReward(uint256 eventId) external nonReentrant whenNotPaused {require(worldId.isVerified(msg.sender),"World ID required"); EventConfig storage e=events[eventId]; require(block.timestamp>e.endTime || e.closed,"not ended"); Position storage p=positions[eventId][msg.sender]; require(p.attended && !p.rewardClaimed,"not eligible"); uint256 amount=e.rewardModel==RewardModel.Fixed?AttendXRewards.reward(p.amount,e.fixedReward,0,0):AttendXRewards.reward(p.amount,0,e.apyBps,e.endTime-e.startTime); require(amount<=e.rewardPool,"pool depleted"); e.rewardPool-=amount; p.rewardClaimed=true; stakingToken.safeTransfer(msg.sender,amount); emit RewardClaimed(msg.sender,eventId,amount);}
    function closeEvent(uint256 eventId) external onlyOwner {events[eventId].closed=true; emit EventClosed(eventId);} function setSlashBps(uint256 bps) external onlyOwner {require(bps<=10_000,"too high"); slashBps=bps;} function pause() external onlyOwner{_pause();} function unpause() external onlyOwner{_unpause();}
}
